CREATE TABLE Atlikejas (
    ID  INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    Sceninis_vardas VARCHAR(100) NOT NULL
);

CREATE TABLE Klausytojas (
    ID  INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    El_pastas VARCHAR(100) NOT NULL
);

CREATE TABLE Albumas (
    ID  INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    Pavadinimas VARCHAR(100) NOT NULL,
    Atlikejas INT NOT NULL,
    Trukme INT, -- sekundės
    Isleidimo_data DATE,
    Dainu_skaicius INT,
    FOREIGN KEY (Atlikejas) REFERENCES Atlikejas ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE TABLE Daina (
    ID  INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    Pavadinimas VARCHAR(100) NOT NULL,
    Trukme INT, -- sekundės
    Isleidimo_data DATE,
    Pamiegta_kartu INT,
    Atlikejas INT NOT NULL,
    Albumas INT,
    FOREIGN KEY (Atlikejas) REFERENCES Atlikejas ON DELETE CASCADE ON UPDATE RESTRICT,
    FOREIGN KEY (Albumas) REFERENCES Albumas ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE TABLE Grojarastis (
    ID  INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    Pavadinimas VARCHAR(100) NOT NULL,
    Dainu_skaicius INT,
    Klausytojas INT NOT NULL,
    FOREIGN KEY (Klausytojas) REFERENCES Klausytojas ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE TABLE Grojarascio_Daina (
    Grojarastis INT NOT NULL,
    Daina INT NOT NULL,
    PRIMARY KEY (Grojarastis, Daina),
    FOREIGN KEY (Grojarastis) REFERENCES Grojarastis ON DELETE CASCADE ON UPDATE RESTRICT,
    FOREIGN KEY (Daina) REFERENCES Daina ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE TABLE Pamegta_Daina (
    Klausytojas INT NOT NULL,
    Daina INT NOT NULL,
    PRIMARY KEY (Klausytojas, Daina),
    FOREIGN KEY (Klausytojas) REFERENCES Klausytojas ON DELETE CASCADE ON UPDATE RESTRICT,
    FOREIGN KEY (Daina) REFERENCES Daina ON DELETE CASCADE ON UPDATE RESTRICT
);
